

-- *1. List the number of films per category.
USE sakila;

SELECT c.name, COUNT(f.film_id) AS numero_de_peliculas
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT s.store_id, ci.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT st.store_id,
       SUM(p.amount) AS total_revenue
FROM payment AS p
JOIN staff AS sf ON p.staff_id = sf.staff_id
JOIN store AS st ON sf.store_id = st.store_id
GROUP BY st.store_id
ORDER BY total_revenue DESC;

SELECT store.store_id,
       city.city AS city,
       SUM(payment.amount) AS total_revenue
FROM payment
JOIN staff ON payment.staff_id = staff.staff_id
JOIN store ON staff.store_id = store.store_id
JOIN address ON store.address_id = address.address_id
JOIN city ON address.city_id = city.city_id
GROUP BY store.store_id, city.city
ORDER BY total_revenue DESC;

-- 4. Determine the average running time of films for each category.

SELECT c.name AS category,
       AVG(f.length) AS avg_length
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON f.film_id = fc.film_id
GROUP BY c.name;

-- Bonus:
-- 1. Identify the film categories with the longest average running time.

SELECT c.name AS category,
       AVG(f.length) AS avg_length
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON f.film_id = fc.film_id
GROUP BY c.name
ORDER BY avg_length DESC;

-- 2. Display the top 10 most frequently rented movies in descending order.

SELECT f.title AS movie_title,
	COUNT(r.rental_id) AS rental_count
FROM rental AS r
JOIN inventory AS i ON r.inventory_id = i.inventory_id
JOIN film AS f ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- 3. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title,
       i.store_id,
       COUNT(i.inventory_id) AS copies_available
FROM film AS f
JOIN inventory AS i ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
GROUP BY f.title, i.store_id;

-- 4. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, 
-- and this information can be obtained using a CASE statement combined with IFNULL."

SELECT f.title AS film_title,
CASE WHEN IFNULL(COUNT(i.inventory_id), 0) > 0 THEN 'Available' ELSE 'NOT available' END AS availability_status
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
GROUP BY f.film_id, f.title
ORDER BY availability_status DESC, f.title;
